### PR TITLE
remove unused logback dependency

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by cstamas** [comment]
Why is there warning in tests about lack of slf4j backend? Which slf4j backed is used not that logback is removed?

**Comment by olamy** [comment]
we need at least one slf4j impl: https://github.com/apache/maven-build-cache-extension/actions/runs/5543308023/job/15013606896?pr=88#step:6:2248

**Comment by gnodet** [comment]
> we need at least one slf4j impl: https://github.com/apache/maven-build-cache-extension/actions/runs/5543308023/job/15013606896?pr=88#step:6:2248

Agreed, what's the purpose of this PR ?

**Comment by elharo** [comment]
1. It cures an unused dependency warning.
2. More importantly it removes yet another idiosyncratic dependency not used anywhere else in maven tossed into the classpath, likely without much thought, some years ago.

https://jlbp.dev/JLBP-1

Logging in Java is a vastly over-engineered mess, and we have only ourselves to blame for it. :-(

**Comment by elharo** [comment]
The warning is an annoying bug in slf4j. We don't need a logging backend in tests. For that matter, we don't need logging in tests. Logging in tests is a *bug*. Only failing tests should generate output, and that output should come from assertion failures. Passing tests should generate no output. Otherwise the actual issues get lost in a sea of irrelevant log junk.

**Review by slachiewicz — APPROVED** [review]

**Comment by olamy** [comment]
-1
Please revert your commit.
It's used only in test and very helpful when you need to debug failing tests locally or even in CI

**Comment by michael-o** [comment]
Slf4j simple is enough here...

**Comment by olamy** [comment]
> Slf4j simple is enough here...

Agree but we need one. I had to debug some issues here in the past with docker on GHA and it was really helpful

**Comment by michael-o** [comment]
> > Slf4j simple is enough here...
> 
> Agree but we need one. I had to debug some issues here in the past with docker on GHA and it was really helpful

That's the purpose of logging...post-mortem assistance  😁

**Comment by HannesWell** [comment]
> > Slf4j simple is enough here...
> 
> Agree but we need one. I had to debug some issues here in the past with docker on GHA and it was really helpful 

You can configure SLF4J-simple via system properties:
https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html
If you want, you can turn it off by default an activate it if needed through corresponding configuration or CLI arguments.

**Comment by olamy** [comment]
logging capability restored here 3b318bbed14703f5d9a539017baefa1060af0310

**Comment by elharo** [comment]
Absolutely. I sent a PR. People responded. No one disapproved the PR by sending a "Request changes" review. I responded to the comments, received an approval from another committer, and merged. That is exactly how it is supposed to go.

What is not supposed to happen is anyone committing anything directly to master and then pushing the branch with no approvals or review. https://github.com/apache/maven-build-cache-extension/commit/3b318bbed14703f5d9a539017baefa1060af0310 could and should have been sent as a PR to be reviewed, and then merged after review and approval like any other change.

**Pull request merged**
