### PR TITLE
Broken Link: Usage of .md causes apache.org documentation 404

### PR DESCRIPTION
**Pull request by mobiuscog**
The last link to "Remote Cache Setup" is correct for viewing in github, but means that the auto-generated webpage (https://maven.apache.org/extensions/maven-build-cache-extension/getting-started.html) on apache.org give a 404 due to a .md extension.
Altering the extension to .html means that the apache.org webpage should work, but navigation within github will be broken.
Therefore, I'm suggesting an absolute link.
Perhaps there is a way to have these links automatically fixed up during webpage creation instead, such that navigation can work both on apache.org and within github.com.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by gnodet** [comment]
@hboutemy do you have any magic suggestion to fix the problem at GitHub + Maven web site ?

**Comment by cstamas** [comment]
-1

it should be `remote-cache.html`

**Review by cstamas — CHANGES_REQUESTED** [review]
Just change the extension from `md` to `html`

**Comment by gnodet** [comment]
> Just change the extension from `md` to `html`

You mean rename the files in the git repo ?

**Comment by hboutemy** [comment]
link fixed in #22

**Pull request closed without merging**
