### PR TITLE
[MBUILDCACHE-81] - Add an option to include project version as part of the cache hash key

### PR DESCRIPTION
**Pull request by igdianov**
Fixes https://issues.apache.org/jira/projects/MBUILDCACHE/issues/MBUILDCACHE-81

- Add new `calculateProjectVersionChecksum` attribute to project versioning cache configuration to enable/disable calculation of the project version checksum input. The default is false to maintain original behavior for cache portability between versions.
- Add/update unit and integration tests to cover possible use cases. 

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [MBUILDCACHE JIRA issue](https://issues.apache.org/jira/browse/MBUILDCACHE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MBUILDCACHE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MBUILDCACHE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by maximilian-novikov-db — APPROVED** [review]

**Comment by olamy** [comment]
I would suggest to change the title of the PR and the jira as well. 
As MBUILDCACHE-76 has not been released but merged only, the release notes will be very confusing as is :)
maybe something saying add an option to add add project version as part of the cache hash key.
wdyt?

**Comment by igdianov** [comment]
> I would suggest to change the title of the PR and the jira as well. As [MBUILDCACHE-76](https://issues.apache.org/jira/browse/MBUILDCACHE-76) has not been released but merged only, the release notes will be very confusing as is :) maybe something saying add an option to add add project version as part of the cache hash key. wdyt?

It makes sense. I updated PR and Jira ticket titles.

**Comment by jira-importer** [comment]
Resolve #309

**Comment by jira-importer** [comment]
Resolve #309

**Pull request merged**
